# Generated by Django 5.0.14 on 2025-07-30 06:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('department_name', models.CharField(choices=[('Corporate Office', 'Corporate Office'), ('Tandur', 'Tandur'), ('Rajban', 'Rajban'), ('Bokajan', 'Bokajan'), ('Akaltara', 'Akaltara'), ('Mandhar', 'Mandhar'), ('Nayagaoun', 'Nayagaoun'), ('Adilabad', 'Adilabad'), ('Kurkunta', 'Kurkunta'), ('Delhi Grinding', 'Delhi Grinding'), ('Bhatinda Grinding', 'Bhatinda Grinding')], help_text='Department this user belongs to', max_length=50)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'Regular User')], default='user', help_text='User role type', max_length=10)),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether this user has admin privileges')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number with country code', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='cci_users_groups', related_query_name='cci_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='cci_users_permissions', related_query_name='cci_user', to='auth.permission')),
            ],
            options={
                'verbose_name': 'CCI User',
                'verbose_name_plural': 'CCI Users',
                'ordering': ['department_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='Unique identifier for the case', max_length=50, unique=True)),
                ('case_name', models.CharField(help_text='Name/title of the case', max_length=255)),
                ('date_of_institution', models.DateField(help_text='Date when the case was instituted')),
                ('parties_involved_complainant', models.TextField(help_text='Details of complainant/applicant parties', max_length=500)),
                ('parties_involved_opposite', models.TextField(help_text='Details of opposite/respondent parties', max_length=500)),
                ('bench', models.CharField(help_text='Bench/Court where case is filed', max_length=100)),
                ('sections_involved', models.CharField(help_text='Legal sections/acts involved', max_length=255)),
                ('status_of_case', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('disposed', 'Disposed'), ('withdrawn', 'Withdrawn'), ('settled', 'Settled'), ('adjourned', 'Adjourned')], default='pending', help_text='Current status of the case', max_length=100)),
                ('type_of_litigation', models.CharField(choices=[('appeal', 'Appeal'), ('writ', 'Writ Petition'), ('complaint', 'Complaint'), ('review', 'Review Petition'), ('contempt', 'Contempt Petition'), ('miscellaneous', 'Miscellaneous')], help_text='Type/category of litigation', max_length=100)),
                ('relief_orders_prayed', models.TextField(help_text='Relief/orders prayed for in the case')),
                ('important_directions_orders', models.TextField(help_text='Important directions/orders issued')),
                ('date_of_next_hearing_order', models.DateField(blank=True, help_text='Date of next hearing/order', null=True)),
                ('date_of_final_order', models.DateField(blank=True, help_text='Date of final order/judgment', null=True)),
                ('outcome', models.TextField(blank=True, help_text='Final outcome of the case', null=True)),
                ('link_of_order_judgment', models.URLField(blank=True, help_text='Link to order/judgment document', max_length=500, null=True)),
                ('department_name', models.CharField(choices=[('Corporate Office', 'Corporate Office'), ('Tandur', 'Tandur'), ('Rajban', 'Rajban'), ('Bokajan', 'Bokajan'), ('Akaltara', 'Akaltara'), ('Mandhar', 'Mandhar'), ('Nayagaoun', 'Nayagaoun'), ('Adilabad', 'Adilabad'), ('Kurkunta', 'Kurkunta'), ('Delhi Grinding', 'Delhi Grinding'), ('Bhatinda Grinding', 'Bhatinda Grinding')], help_text='Department responsible for this case', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the case', max_length=10)),
                ('case_value', models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value involved in the case', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_count', models.PositiveIntegerField(default=0, help_text='Number of documents attached')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='User who last updated this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Litigation Case',
                'verbose_name_plural': 'Litigation Cases',
                'ordering': ['-date_of_institution', 'case_id'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Case note/comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=True, help_text='Internal note (not visible to external parties)')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='litigation_api.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['department_name'], name='litigation__departm_445ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status_of_case'], name='litigation__status__e674b3_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['date_of_institution'], name='litigation__date_of_a7c86e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_by'], name='litigation__created_ad13f6_idx'),
        ),
    ]
