# Generated by Django 5.0.1 on 2025-08-04 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_type', models.CharField(choices=[('case', 'Case Draft'), ('user', 'User Draft'), ('other', 'Other Draft')], default='case', help_text='Type of draft (case, user, etc.)', max_length=10)),
                ('title', models.CharField(help_text='User-friendly title for the draft', max_length=200)),
                ('form_data', models.JSONField(help_text='Draft form data as JSON')),
                ('case_id', models.CharField(blank=True, help_text='Case ID if editing existing case', max_length=50, null=True)),
                ('draft_key', models.CharField(help_text='Unique key for frontend identification', max_length=100, unique=True)),
                ('is_auto_saved', models.BooleanField(default=True, help_text='Whether this was auto-saved or manually saved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this draft', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'draft_type'], name='litigation__user_id_1ed980_idx'), models.Index(fields=['user', 'case_id'], name='litigation__user_id_7d12c7_idx'), models.Index(fields=['draft_key'], name='litigation__draft_k_ab8594_idx')],
                'unique_together': {('user', 'draft_key')},
            },
        ),
    ]
