# Generated by Django 5.0.1 on 2025-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='status_of_case',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_hearing', 'Under Hearing'), ('admitted', 'Admitted'), ('disposed', 'Disposed'), ('closed', 'Closed'), ('dismissed', 'Dismissed'), ('settled', 'Settled'), ('withdrawn', 'Withdrawn')], default='pending', help_text='Current status of the case', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='type_of_litigation',
            field=models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('constitutional', 'Constitutional'), ('commercial', 'Commercial'), ('tax', 'Tax'), ('labor', 'Labor'), ('environmental', 'Environmental'), ('consumer', 'Consumer'), ('administrative', 'Administrative'), ('others', 'Others')], help_text='Type/category of litigation', max_length=100),
        ),
    ]
