# Generated by Django 5.0.1 on 2025-09-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation_api', '0002_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(help_text='Case type (CS, WP, SLP, etc.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='internal_department',
            field=models.CharField(help_text='Internal CCI department handling the case', max_length=50),
        ),
    ]
